/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as userRouteImport } from './routes/(user)/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as userIndexImport } from './routes/(user)/index'
import { Route as AdminUserImport } from './routes/admin/user'
import { Route as AdminAnalyticImport } from './routes/admin/analytic'
import { Route as userTrashImport } from './routes/(user)/trash'
import { Route as userRecentImport } from './routes/(user)/recent'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as userSettingProfileImport } from './routes/(user)/setting.profile'
import { Route as userFolderIdImport } from './routes/(user)/folder.$id'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const userRouteRoute = userRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const userIndexRoute = userIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => userRouteRoute,
} as any)

const AdminUserRoute = AdminUserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAnalyticRoute = AdminAnalyticImport.update({
  id: '/analytic',
  path: '/analytic',
  getParentRoute: () => AdminRouteRoute,
} as any)

const userTrashRoute = userTrashImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => userRouteRoute,
} as any)

const userRecentRoute = userRecentImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => userRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const userSettingProfileRoute = userSettingProfileImport.update({
  id: '/setting/profile',
  path: '/setting/profile',
  getParentRoute: () => userRouteRoute,
} as any)

const userFolderIdRoute = userFolderIdImport.update({
  id: '/folder/$id',
  path: '/folder/$id',
  getParentRoute: () => userRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/(user)': {
      id: '/(user)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/(user)/recent': {
      id: '/(user)/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof userRecentImport
      parentRoute: typeof userRouteImport
    }
    '/(user)/trash': {
      id: '/(user)/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof userTrashImport
      parentRoute: typeof userRouteImport
    }
    '/admin/analytic': {
      id: '/admin/analytic'
      path: '/analytic'
      fullPath: '/admin/analytic'
      preLoaderRoute: typeof AdminAnalyticImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserImport
      parentRoute: typeof AdminRouteImport
    }
    '/(user)/': {
      id: '/(user)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userIndexImport
      parentRoute: typeof userRouteImport
    }
    '/(user)/folder/$id': {
      id: '/(user)/folder/$id'
      path: '/folder/$id'
      fullPath: '/folder/$id'
      preLoaderRoute: typeof userFolderIdImport
      parentRoute: typeof userRouteImport
    }
    '/(user)/setting/profile': {
      id: '/(user)/setting/profile'
      path: '/setting/profile'
      fullPath: '/setting/profile'
      preLoaderRoute: typeof userSettingProfileImport
      parentRoute: typeof userRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface userRouteRouteChildren {
  userRecentRoute: typeof userRecentRoute
  userTrashRoute: typeof userTrashRoute
  userIndexRoute: typeof userIndexRoute
  userFolderIdRoute: typeof userFolderIdRoute
  userSettingProfileRoute: typeof userSettingProfileRoute
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userRecentRoute: userRecentRoute,
  userTrashRoute: userTrashRoute,
  userIndexRoute: userIndexRoute,
  userFolderIdRoute: userFolderIdRoute,
  userSettingProfileRoute: userSettingProfileRoute,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticRoute: typeof AdminAnalyticRoute
  AdminUserRoute: typeof AdminUserRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticRoute: AdminAnalyticRoute,
  AdminUserRoute: AdminUserRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof userIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/recent': typeof userRecentRoute
  '/trash': typeof userTrashRoute
  '/admin/analytic': typeof AdminAnalyticRoute
  '/admin/user': typeof AdminUserRoute
  '/folder/$id': typeof userFolderIdRoute
  '/setting/profile': typeof userSettingProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof userIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/recent': typeof userRecentRoute
  '/trash': typeof userTrashRoute
  '/admin/analytic': typeof AdminAnalyticRoute
  '/admin/user': typeof AdminUserRoute
  '/folder/$id': typeof userFolderIdRoute
  '/setting/profile': typeof userSettingProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(user)/recent': typeof userRecentRoute
  '/(user)/trash': typeof userTrashRoute
  '/admin/analytic': typeof AdminAnalyticRoute
  '/admin/user': typeof AdminUserRoute
  '/(user)/': typeof userIndexRoute
  '/(user)/folder/$id': typeof userFolderIdRoute
  '/(user)/setting/profile': typeof userSettingProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/recent'
    | '/trash'
    | '/admin/analytic'
    | '/admin/user'
    | '/folder/$id'
    | '/setting/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/recent'
    | '/trash'
    | '/admin/analytic'
    | '/admin/user'
    | '/folder/$id'
    | '/setting/profile'
  id:
    | '__root__'
    | '/(auth)'
    | '/(user)'
    | '/admin'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(user)/recent'
    | '/(user)/trash'
    | '/admin/analytic'
    | '/admin/user'
    | '/(user)/'
    | '/(user)/folder/$id'
    | '/(user)/setting/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(user)",
        "/admin"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login",
        "/(auth)/register"
      ]
    },
    "/(user)": {
      "filePath": "(user)/route.tsx",
      "children": [
        "/(user)/recent",
        "/(user)/trash",
        "/(user)/",
        "/(user)/folder/$id",
        "/(user)/setting/profile"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/analytic",
        "/admin/user"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/(user)/recent": {
      "filePath": "(user)/recent.tsx",
      "parent": "/(user)"
    },
    "/(user)/trash": {
      "filePath": "(user)/trash.tsx",
      "parent": "/(user)"
    },
    "/admin/analytic": {
      "filePath": "admin/analytic.tsx",
      "parent": "/admin"
    },
    "/admin/user": {
      "filePath": "admin/user.tsx",
      "parent": "/admin"
    },
    "/(user)/": {
      "filePath": "(user)/index.tsx",
      "parent": "/(user)"
    },
    "/(user)/folder/$id": {
      "filePath": "(user)/folder.$id.tsx",
      "parent": "/(user)"
    },
    "/(user)/setting/profile": {
      "filePath": "(user)/setting.profile.tsx",
      "parent": "/(user)"
    }
  }
}
ROUTE_MANIFEST_END */
