/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as userRouteImport } from './routes/(user)/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as userIndexImport } from './routes/(user)/index'
import { Route as userTrashImport } from './routes/(user)/trash'
import { Route as userRecentImport } from './routes/(user)/recent'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as userFolderIdImport } from './routes/(user)/folder/$id'

// Create/Update Routes

const userRouteRoute = userRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const userIndexRoute = userIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => userRouteRoute,
} as any)

const userTrashRoute = userTrashImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => userRouteRoute,
} as any)

const userRecentRoute = userRecentImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => userRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const userFolderIdRoute = userFolderIdImport.update({
  id: '/folder/$id',
  path: '/folder/$id',
  getParentRoute: () => userRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/(user)': {
      id: '/(user)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/(user)/recent': {
      id: '/(user)/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof userRecentImport
      parentRoute: typeof userRouteImport
    }
    '/(user)/trash': {
      id: '/(user)/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof userTrashImport
      parentRoute: typeof userRouteImport
    }
    '/(user)/': {
      id: '/(user)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userIndexImport
      parentRoute: typeof userRouteImport
    }
    '/(user)/folder/$id': {
      id: '/(user)/folder/$id'
      path: '/folder/$id'
      fullPath: '/folder/$id'
      preLoaderRoute: typeof userFolderIdImport
      parentRoute: typeof userRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface userRouteRouteChildren {
  userRecentRoute: typeof userRecentRoute
  userTrashRoute: typeof userTrashRoute
  userIndexRoute: typeof userIndexRoute
  userFolderIdRoute: typeof userFolderIdRoute
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userRecentRoute: userRecentRoute,
  userTrashRoute: userTrashRoute,
  userIndexRoute: userIndexRoute,
  userFolderIdRoute: userFolderIdRoute,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof userIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/recent': typeof userRecentRoute
  '/trash': typeof userTrashRoute
  '/folder/$id': typeof userFolderIdRoute
}

export interface FileRoutesByTo {
  '/': typeof userIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/recent': typeof userRecentRoute
  '/trash': typeof userTrashRoute
  '/folder/$id': typeof userFolderIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(user)/recent': typeof userRecentRoute
  '/(user)/trash': typeof userTrashRoute
  '/(user)/': typeof userIndexRoute
  '/(user)/folder/$id': typeof userFolderIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/recent' | '/trash' | '/folder/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/recent' | '/trash' | '/folder/$id'
  id:
    | '__root__'
    | '/(auth)'
    | '/(user)'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(user)/recent'
    | '/(user)/trash'
    | '/(user)/'
    | '/(user)/folder/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(user)"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login",
        "/(auth)/register"
      ]
    },
    "/(user)": {
      "filePath": "(user)/route.tsx",
      "children": [
        "/(user)/recent",
        "/(user)/trash",
        "/(user)/",
        "/(user)/folder/$id"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/(user)/recent": {
      "filePath": "(user)/recent.tsx",
      "parent": "/(user)"
    },
    "/(user)/trash": {
      "filePath": "(user)/trash.tsx",
      "parent": "/(user)"
    },
    "/(user)/": {
      "filePath": "(user)/index.tsx",
      "parent": "/(user)"
    },
    "/(user)/folder/$id": {
      "filePath": "(user)/folder/$id.tsx",
      "parent": "/(user)"
    }
  }
}
ROUTE_MANIFEST_END */
