import { 
  ArrowUp, 
  File, 
  Folder, 
  Image, 
  Music, 
  Video,
  Code,
  FileText,
  FilePen,
  Calculator,
  Calendar,
  Book,
  BookOpen,
  Bookmark,
  Mail,
  MessageSquare,
  Settings,
  User,
  Users,
  Heart,
  Star,
  Clock,
  Timer,
  Cloud,
  Download,
  Upload,
  Link,
  Globe,
  Terminal,
  Zap,
  Coffee
} from "lucide-react";

// Remove Document since it wasn't imported
const WorkspaceIcons = {
  arrowUp: ArrowUp,
  file: File,
  image: Image,
  music: Music,
  video: Video,
  folder: Folder,
  code: Code,
  fileText: FileText,
  filePen: FilePen,
  calculator: Calculator,
  calendar: Calendar,
  book: Book,
  bookOpen: BookOpen,
  bookmark: Bookmark,
  mail: Mail,
  message: MessageSquare,
  settings: Settings,
  user: User,
  users: Users,
  heart: Heart,
  star: Star,
  clock: Clock,
  timer: Timer,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  link: Link,
  globe: Globe,
  terminal: Terminal,
  zap: Zap,
  coffee: Coffee
};

export type WorkspaceIconType = keyof typeof WorkspaceIcons;
export default WorkspaceIcons;