services:
  mongodb:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUser
      MONGO_INITDB_ROOT_PASSWORD: myPass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
